<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>AuthorizeNet</AssemblyName>
    <RootNamespace>AuthorizeNet</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>0219,1591,1635</NoWarn>
    <AssemblyTitle>Official .NET SDK for Authorize.Net</AssemblyTitle>
    <AssemblyDescription>Official .NET SDK for Authorize.Net</AssemblyDescription>
    <AssemblyCompany>Visa Inc</AssemblyCompany>
    <AssemblyProduct>Official .NET SDK for Authorize.Net</AssemblyProduct>
    <AssemblyCopyright>Copyright © Visa Inc 2018</AssemblyCopyright>
    <AssemblyVersion>2.0.4.0</AssemblyVersion>
    <FileVersion>2.0.4.0</FileVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Api\Controllers\createFingerPrintController.cs" />
    <Compile Remove="Api\Controllers\transactionResponseEmvController.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Api\ControllerTemplate.cst" />
  </ItemGroup>

</Project>