@ECHO OFF

@ECHO Generating enum tests
SET SRCDIR=Authorize.NET\Api\Contracts\V1
IF NOT EXIST "%SRCDIR%" (
    @ECHO "%SRCDIR%" Does not exist
    EXIT /b 1
)
SET CYGWIN=NODOSFILEWARNING
SET OUTFILE=%TEMP%\AllGeneratedEnumTest.cs
SET TEMPLATE=%CD%\scripts\EnumTemplate.cst
PUSHD "%SRCDIR%"
grep -i "public enum" AnetApiSchema.generated.cs | cut -c17- | cut -f1 -d" " > %TEMP%\enum.lst

@ECHO.> "%OUTFILE%"
@ECHO         //Generated by cs-enum-test on %date%-%time% >> "%OUTFILE%"
@ECHO         [TestMethod] >> "%OUTFILE%"
@ECHO         public void AllEnumTest() >> "%OUTFILE%"
@ECHO         {>> "%OUTFILE%"
@ECHO.
@ECHO.

FOR /f %%x IN ( %TEMP%\enum.lst) DO (
    @ECHO Processing %%x;
    COPY %TEMPLATE% %TEMP%\%%x.cs 1>NUL
	perl -pi -w -e 's/ENUMNAME/%%x/g;' %TEMP%\%%x.cs 2>NUL
    TYPE %TEMP%\%%x.cs >> "%OUTFILE%"
)
@ECHO         } >> "%OUTFILE%"
@ECHO.>> "%OUTFILE%"
POPD
@ECHO.
@ECHO.
@ECHO The generated test is in "%OUTFILE%"
